name: Daily Commit

# Trigger the workflow daily at 11:30 AM UTC (adjust as needed)
on:
  schedule:
    - cron: "30 11 * * *"

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make changes (e.g., update a file with the current date)
      - name: Update date in file
        run: echo "Last run on $(date)" > last_run.txt

      # Step 3: Configure Git user details
      - name: Set Git user details
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "22f3002175@ds.study.iitm.ac.in"

      # Step 4: Commit and push changes
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily update - $(date)"
          branch: main # Replace with your default branch if different
