

name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure this line is added

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          # Your command to make changes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit message
